### ISSUE TITLE
Android resource not found exception

### ISSUE THREAD

**Issue by tranb3r** [muak/AiForms.Maui.SettingsView#5]
Hi,
On Android, there is an exception when using this package.
```
Android.Content.Res.Resources+NotFoundException: Resource ID #0x7f0b0034
at Java.Interop.JniEnvironment.InstanceMethods.CallObjectMethod(JniObjectReference instance, JniMethodInfo method, JniArgumentValue* args) in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/obj/Release/net7.0/JniEnvironment.g.cs:line 11524
at Java.Interop.JniPeerMembers.JniInstanceMethods.InvokeVirtualObjectMethod(String encodedMember, IJavaPeerable self, JniArgumentValue* parameters) in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/Java.Interop/JniPeerMembers.JniInstanceMethods_Invoke.cs:line 867
at Android.Views.LayoutInflater.Inflate(Int32 resource, ViewGroup root, Boolean attachToRoot) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net7.0/android-33/mcw/Android.Views.LayoutInflater.cs:line 696
at AiForms.Settings.Platforms.Droid.SettingsViewRecyclerAdapter.OnCreateViewHolder(ViewGroup parent, Int32 viewType)
```
No error when using 0.1.11-pre. This seems to be a regression in 0.1.12-pre.

Could you please take a look ? 
Thank you

**Comment by tranb3r** [comment]
@muak 
Any idea what's happening?

**Comment by tranb3r** [comment]
Hi @muak 
I've prepared a PR with a fix for this issue.
Could you please review it?
Thanks

**Comment by muak** [comment]
@tranb3r 

Thank you for your pull request!
Please wait for a while so I will confirm it.
